
--STG TABLES 

CREATE TABLE [CCDW_STG].[dbo].[CUSTOMERS]
(
NAME VARCHAR(255) NOT NULL,
CUST_ID VARCHAR(18) PRIMARY KEY,
OPEN_DT DATE NOT NULL,
CONSULT_DT DATE,
VAC_ID CHAR(5),
DR_NAME CHAR(255),
STATE CHAR(5),
COUNTRY CHAR(5),
FLAG CHAR(1)
)


-----

CREATE TABLE [CCDW_STG].[dbo].[JOB_STATUS]
(
JOB_ID BIGINT IDENTITY PRIMARY KEY,
JOB_NAME VARCHAR(30),
FILE_MISSING INT,
JOB_PASS_FAIL INT,
JOB_START DATETIME2(3),
JOB_END DATETIME2(3),
OPDATE DATE,
COMMENTS VARCHAR(4000),
LOAD_DATE DATE
)

-----

CREATE TABLE [CCDW_STG].[dbo].[RAW_FILE_DETAILS]
(
JOB_NAME VARCHAR(30),
FILE_NAME VARCHAR(100),
FILE_EXTENSION VARCHAR(10),
FOLDER_LOCATION VARCHAR(500),
DESCRIPTION VARCHAR(1000),
LOAD_DATE DATE
)


INSERT INTO [CCDW_STG].[dbo].[RAW_FILE_DETAILS] 
VALUES
('CUST_GLOBAL','CUSTOMER_GLOBAL','.txt','C:\Users\Arghya\Desktop\Incubyte\DATA','This job is to split hospital customer data based on country',getdate())

-----

--THIS TABLE IS USED FOR MAPPING

CREATE TABLE [CCDW_STG].[dbo].[CUST_COUNTRY_CONFIG]
(
COUNTRY CHAR(5),
RW_TABLE VARCHAR(50),
)

INSERT INTO [CCDW_STG].[dbo].[CUST_COUNTRY_CONFIG]
VALUES
('USA','CUST_UNITED_STATES'),
('IND','CUST_INDIA'),
('PHIL','CUST_PHILIPPINES'),
('AU','CUST_AUSTRALIA')


-----
--CREATE STG TABLE FOR UNMAPPED DATA

CREATE TABLE [CCDW_STG].[dbo].[CUSTOMERS_NOT_MAPPED]
(
NAME VARCHAR(255) NOT NULL,
CUST_ID VARCHAR(18) PRIMARY KEY,
OPEN_DT DATE NOT NULL,
CONSULT_DT DATE,
VAC_ID CHAR(5),
DR_NAME CHAR(255),
STATE CHAR(5),
COUNTRY CHAR(5),
FLAG CHAR(1)
)

------------------------------------------------------------------------------------------------------------------
--RW TABLES

--AU
CREATE TABLE [CCDW_RW].[dbo].[CUST_AUSTRALIA]
(
NAME VARCHAR(255) NOT NULL,
CUST_ID VARCHAR(18) PRIMARY KEY,
OPEN_DT DATE NOT NULL,
CONSULT_DT DATE,
VAC_ID CHAR(5),
DR_NAME CHAR(255),
STATE CHAR(5),
COUNTRY CHAR(5),
FLAG CHAR(1)
)

--IN
CREATE TABLE [CCDW_RW].[dbo].[CUST_INDIA]
(
NAME VARCHAR(255) NOT NULL,
CUST_ID VARCHAR(18) PRIMARY KEY,
OPEN_DT DATE NOT NULL,
CONSULT_DT DATE,
VAC_ID CHAR(5),
DR_NAME CHAR(255),
STATE CHAR(5),
COUNTRY CHAR(5),
FLAG CHAR(1)
)

--PHIL
CREATE TABLE [CCDW_RW].[dbo].[CUST_PHILIPPINES]
(
NAME VARCHAR(255) NOT NULL,
CUST_ID VARCHAR(18) PRIMARY KEY,
OPEN_DT DATE NOT NULL,
CONSULT_DT DATE,
VAC_ID CHAR(5),
DR_NAME CHAR(255),
STATE CHAR(5),
COUNTRY CHAR(5),
FLAG CHAR(1)
)

--US
CREATE TABLE [CCDW_RW].[dbo].[CUST_UNITED_STATES]
(
NAME VARCHAR(255) NOT NULL,
CUST_ID VARCHAR(18) PRIMARY KEY,
OPEN_DT DATE NOT NULL,
CONSULT_DT DATE,
VAC_ID CHAR(5),
DR_NAME CHAR(255),
STATE CHAR(5),
COUNTRY CHAR(5),
FLAG CHAR(1)
)

----------------------------


--STORED PROCEDURE
-----------------------------
GO

USE [CCDW_RW]
GO
CREATE PROCEDURE [dbo].[CUST_STG_TO_RW] @STG_LOAD_DATA VARCHAR(30)='CUSTOMERS'
AS

BEGIN

		--DECLARE VARIABLE @SQL_QUERY TO STORE QUERY TEXT
		DECLARE @SQL_QUERY NVARCHAR(MAX)

		--------------------------------------------------------------------
		--INSERT UNMAPPEDDATA IN CUSTOMERS TABLE
		DECLARE @CUSTOMERS_NOT_MAPPED_COUNT INT
		SELECT @CUSTOMERS_NOT_MAPPED_COUNT = COUNT(*) FROM [CCDW_STG].[dbo].[CUSTOMERS_NOT_MAPPED]

		IF @CUSTOMERS_NOT_MAPPED_COUNT > 0
		BEGIN
		INSERT INTO [CCDW_STG].[dbo].[CUSTOMERS]
		SELECT * FROM [CCDW_STG].[dbo].[CUSTOMERS_NOT_MAPPED]

		DELETE FROM [CCDW_STG].[dbo].[CUSTOMERS_NOT_MAPPED]
		END


		---------------------------------------------------------------------
		-- CREATE #CUSTOMER TABLE TO STORE ALL CUSTOMER DATA LINKED WITH RW_TABLE

		SELECT CUSTOMER.*,TABLE_MAPPER.RW_TABLE 
		INTO #CUSTOMERS FROM [CCDW_STG].[dbo].[CUSTOMERS] CUSTOMER
		LEFT JOIN [CCDW_STG].[dbo].[CUST_COUNTRY_CONFIG] TABLE_MAPPER
		ON CUSTOMER.COUNTRY=TABLE_MAPPER.COUNTRY

		----------------------------------------------------------------------

		--CREATE CURSOR TABLE_NAME_CURSOR TO LOAD THE DATA IN MARKET TABLE

		DECLARE @TABLE_NAME NVARCHAR(50);
 
		DECLARE TABLE_NAME_CURSOR CURSOR
		FOR
		SELECT DISTINCT RW_TABLE FROM #CUSTOMERS WHERE RW_TABLE IS NOT NULL
 
		OPEN TABLE_NAME_CURSOR;
 
		FETCH NEXT FROM TABLE_NAME_CURSOR INTO @TABLE_NAME
 
		WHILE @@FETCH_STATUS = 0
			BEGIN
  
	  
			  SET @SQL_QUERY= N'INSERT INTO [CCDW_RW].[dbo].'+QUOTENAME(@TABLE_NAME)+'
			  SELECT NAME,CUST_ID,OPEN_DT,CONSULT_DT,VAC_ID,DR_NAME,STATE,COUNTRY,FLAG
			  FROM #CUSTOMERS WHERE RW_TABLE ='''+@TABLE_NAME+''''

			  EXEC sp_executesql @SQL_QUERY
 
			  FETCH NEXT  FROM TABLE_NAME_CURSOR  INTO @TABLE_NAME
			END

		CLOSE TABLE_NAME_CURSOR
 
		DEALLOCATE TABLE_NAME_CURSOR

		--END OF CURSOR
		------------------------------------------------------------------------
		--LOAD UNMAPPED DATA IN 

		INSERT INTO [CCDW_STG].[dbo].[CUSTOMERS_NOT_MAPPED]
		SELECT NAME,CUST_ID,OPEN_DT,CONSULT_DT,VAC_ID,DR_NAME,STATE,COUNTRY,FLAG
		FROM #CUSTOMERS WHERE RW_TABLE IS NULL

		--END OF LOADING IN CUSTOMERS_NOT_MAPPED TABLE

		------------------------------------------------------------------------
		--DROP TEMPORARY TABLE 
		DROP TABLE #CUSTOMERS

		-- DELETE STG TABLE AFTER RUNNING THIS SP SEPERATELY FOR CUSTOMERS_NOT_MAPPED DATA
		IF @STG_LOAD_DATA = 'CUSTOMERS_NOT_MAPPED'
		BEGIN
			DELETE FROM [CCDW_STG].[dbo].[CUSTOMERS]
		END

END





