--CHECK IF [CCDW_STG].[dbo].[CUSTOMERS] TABLE EXISTS
USE [CCDW_STG]
GO
IF OBJECT_ID('[dbo].[CUSTOMERS]') IS NOT NULL
BEGIN
PRINT 'Table exists.'
END
ELSE
BEGIN
PRINT 'Table does not exist.'
END

--CHECK IF [CCDW_STG].[dbo].[CUST_COUNTRY_CONFIG] EXISTS
USE [CCDW_STG]
GO
IF OBJECT_ID('[dbo].[CUST_COUNTRY_CONFIG]') IS NOT NULL
BEGIN
PRINT 'Table exists.'
END
ELSE
BEGIN
PRINT 'Table does not exist.'
END

--CHECK IF [CCDW_STG].[dbo].[JOB_STATUS] EXISTS

USE [CCDW_STG]
GO
IF OBJECT_ID('[dbo].[JOB_STATUS]') IS NOT NULL
BEGIN
PRINT 'Table exists.'
END
ELSE
BEGIN
PRINT 'Table does not exist.'
END

--CHECK IF [CCDW_STG].[dbo].[RAW_FILE_DETAILS] EXISTS

USE [CCDW_STG]
GO
IF OBJECT_ID('[dbo].[RAW_FILE_DETAILS]') IS NOT NULL
BEGIN
PRINT 'Table exists.'
END
ELSE
BEGIN
PRINT 'Table does not exist.'
END


--INSERT DATA AND UPDATE JOB_STATUS

--//CHECK JOB_STATUS
SELECT * FROM [CCDW_STG].[dbo].[JOB_STATUS]

--//CHECK_DATA in [CCDW_STG].[dbo].[CUSTOMERS]
SELECT * FROM [CCDW_STG].[dbo].[CUSTOMERS]

--//CHECK ON EXCEPTION WHETHER JOB_STATUS IS UPDATED
SELECT * FROM [CCDW_STG].[dbo].[JOB_STATUS]

--CHECK MARKET TABLE IN RW DATABASE 

--1. CREATE CUSTOMER_CONFIG
SELECT * FROM [CCDW_STG].[dbo].[CUST_COUNTRY_CONFIG]

--2. CREATE MARKET_SPECIFIC TABLE
SELECT * FROM [CCDW_RW].[dbo].CUST_UNITED_STATES
SELECT * FROM [CCDW_RW].[dbo].CUST_INDIA
SELECT * FROM [CCDW_RW].[dbo].CUST_PHILIPPINES
SELECT * FROM [CCDW_RW].[dbo].CUST_AUSTRALIA

--3.CREATE TABLE IN STG WHICH WOULD CONTAIN DATA THAT ARE NOT MAPPED
SELECT * FROM [CCDW_STG].[dbo].[CUSTOMERS_NOT_MAPPED]

--4. CREATE SP TO LOAD DATA IN RW MARKET TABLE AND MOVE DATA TO CUSTOMERS_NOT_MAPPED FOR NO MAPPING DATA

--check whether data is moving to #customer - True

--check whether data is moving to market table - True

--check whether unmapped data is moving to seperate table - True

USE CCDW_RW 
EXEC [dbo].[CUST_STG_TO_RW]

-- check whether data is getting processed from CUSTOMERS_NOT_MAPPED - True
-- 1. move to stg 2. delete CUSTOMERS_NOT_MAPPED table 3. process stg data normally 4. later delete stg data

USE CCDW_RW
EXEC [dbo].[CUST_STG_TO_RW] 'CUSTOMERS_NOT_MAPPED'

--CHECK WHETHER SSIS IS LOADING 'CUSTOMERS_NOT_MAPPED' DATA IN STG BEFORE PROCESSING CUSTOMER STG TABLE - True 
